import { FontConfig } from "@/configs/font.config";
import { locales } from "@/configs/i18n.config";
import { cn } from "@/lib/utils";
import "@/styles/global.css";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import type { LayoutProps } from "@/types/component.types";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const generateStaticParams = async () => {
	return locales.map((locale) => ({ locale }));
};

const RootLayout = async ({ children, params }: LayoutProps) => {
	const { locale } = await params;
	setRequestLocale(locale);

	if (!hasLocale(locales, locale)) {
		return notFound();
	}

	return (
		<html lang={locale} className={cn(FontConfig.className, "scroll-smooth")}>
			<body>
				{/* <RQProvider> */}
				<NextIntlClientProvider>
					{/* <NuqsAdapter> */}
					{children}
					{/* </NuqsAdapter> */}
				</NextIntlClientProvider>
				{/* </RQProvider> */}
			</body>
		</html>
	);
};

export default RootLayout;
